name: dependencies
description: "A new Flutter package project."
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

  flutter_micro_basis:
    git:
      url: "https://github.com/ladans-io/flutter_micro_basis"
      ref: v3
  bloc_basis:
    git:
      url: "https://github.com/ladans-io/bloc_basis"
      ref: v2
  shared_preferences: ^2.0.18
  http: ^1.0.0
  equatable: ^2.0.5
  intl: ^0.19.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  async: ^2.11.0
  share_plus: ^10.1.2
  firebase_remote_config: ^5.2.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  firebase_crashlytics: ^4.2.0
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.248
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.0.0
  borsh: ^0.3.1+4
  borsh_annotation: ^0.3.1+5
  solana_web3: ^0.1.3
  file_picker: ^8.0.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  visibility_detector: ^0.4.0+2
  video_thumbnail: ^0.5.3
  photo_view: ^0.15.0
  uuid: ^4.4.2
  iconsax: ^0.0.8
  ionicons: ^0.2.2
  pull_down_button: ^0.10.1
  detectable_text_field: ^3.0.2
  flutter_local_notifications: ^17.2.3
  custom_refresh_indicator: ^4.0.1
  dismissible_page:
    path: ./../building_blocks/dismissible_page
  image_editor_plus:
    path: ./../building_blocks/image_editor_plus
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.3
  metrics_for_dart_code:
    git:
      url: "https://github.com/ladans-io/metrics_for_dart_code"

flutter: